<a href="https://colab.research.google.com/github/Preethigit7/project/blob/main/Copy_of_Untitled6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5])
print("array:",arr)
print("sum",np.sum(arr))
print("mean",np.mean(arr))


array: [1 2 3 4 5]
sum 15
mean 3.0


In [ ]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.zeros((2,3))
arr3 = np.ones((2,3))
arr4 = np.arange(0,10,2)
arr5 = np.linspace(0,1,5)

print(arr1)
print(arr2)
print(arr3)
print(arr4)
print(arr5)

print("shape of arr1",arr1.shape)
reshaped_arr1 = arr1.reshape(5,1)
print("reshape of arr1",reshaped_arr1)
print(max(arr1))

[1 2 3 4 5]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]
shape of arr1 (5,)
reshape of arr1 [[1]
 [2]
 [3]
 [4]
 [5]]
5
